### ISSUE TITLE
Make it possible to supply an existing py4j gateway object

### ISSUE THREAD

**Issue by agronholm** [massmutual/py4jdbc#10]
Always spawning a new JVM doesn't make sense if the application has other uses for py4j too. This would also make integration possible with projects like [asphalt-py4j](https://github.com/asphalt-framework/asphalt-py4j).

**Comment by twneale** [comment]
Hi @agronholm, this is already a feature! You can pass an existing gateway object to py4jdbc.connect (See https://github.com/massmutual/py4jdbc/blob/master/py4jdbc/dbapi2.py#L16). Please give it a try and let me know if it doesn't work the way you expected.

**Comment by agronholm** [comment]
My apologies, I missed this!
