### ISSUE TITLE
SyntaxError on Import

### ISSUE THREAD

**Issue by seanlaw** [massmutual/py4jdbc#12]
I did a pip install and

```
import py4jdbc
```

Causes the following error:

```
File "~/anaconda/lib/python2.7/site-packages/py4jdbc/dbapi2.py", line 112
def get_property(self, name: str):
                           ^
SyntaxError: invalid syntax
```

**Comment by seanlaw** [comment]
I am running Python 2.7.11. Does this package only work with Python 3?

**Comment by agronholm** [comment]
The classifiers in `setup.py` indicate support for Python 3.3 and up. So yeah.

**Comment by twneale** [comment]
Correct, @seanlaw sorry for the inconvenience--I added a heads-up warning about lack of python 2 compatibility in the readme (abd5eb3).
