### ISSUE TITLE
How to pass jars as a parameter when connecting to a database?

### ISSUE THREAD

**Issue by dclong** [massmutual/py4jdbc#19]
Or is there any global configuration file for location of jars?

**Comment by rschwager-mm** [comment]
While there isn't such a parameter to `py4jdbc.connect`, you can export a colon separated list of your jars to the `CLASSPATH` variable and use `py4jdbc.connect` with no modifications.
Something like `CLASSPATH=/path/to/a.jar:/path/to/b.jar python myjdbcscript.py` should do the trick.

**Comment by rschwager-mm** [comment]
I'm going to close this issue for now, please re-open it if you get stuck.

**Comment by dclong** [comment]
@rschwager-mm,

I followed your instructions and can connect to Teradata but I got the following errors when running a simple query. Do you have any idea what went wrong?

Exception: Launching GatewayServer failed with exit code 1!
