### ISSUE TITLE
resultset._Row._replace(**kwds) bug?

### ISSUE THREAD

**Issue by merritts** [massmutual/py4jdbc#7]
When I try to update values of existing fields in a _Row object using the _replace method, I receive the following exception. The fields I am trying to replace are listed in the ```stuff``` dictionary below.
```
stuff = {'STREET_ADDRESS_1': '1 Main St', 'CITY': 'Westfield', 'ZIP': '01085', 'STATE': 'MA'}
orig._replace(**stuff)
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/py4jdbc/resultset.py", line 151, in _replace
    result = self._make(map(kwds.pop, self._fieldnames, _self))
NameError: name '_self' is not defined
```

**Comment by twneale** [comment]
@merritts So this is a definite bug--I pasted the full generate code of collections.namedtuple into py4jdbc so I could customize aspects of it, and looks like I neglected this piece. Here's the culprit https://github.com/massmutual/py4jdbc/blob/master/py4jdbc/resultset.py#L151

**Comment by twneale** [comment]
Accidentally closed and re-opened, @merritts Can you try re-installing from master (i.e., not from pip) and try again?

**Comment by merritts** [comment]
This is all set.
